# Generated by Django 3.2.19 on 2023-06-30 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0003_alter_follower_followed_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followed_location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='followed_location', to='locations.location'),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'followed', 'followed_location')},
        ),
    ]
