# Generated by Django 3.2.19 on 2023-06-30 14:11

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('followers', '0008_alter_follower_followed_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followed_location',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='locations.location'),
        ),
    ]
